#!/bin/bash -eu

PS4='[ $(date +%T) ] '
set -x

: = $0: BEGIN

trap ': = $0: FAIL' ERR

: == Generate SD/MMC card to boot Android

cd $HOME/rowboat-android

: ==== provide the boot commands and boot arguments.

cat << __EOF__ > uEnv.txt
bootargs=console=ttyO0,115200n8 androidboot.console=ttyO0 mem=256M root=/dev/mmcblk0p2 rw rootfstype=ext3 rootwait init=/init ip=off
bootcmd=mmc rescan ; fatload mmc 0 81000000 uImage ; bootm 81000000
uenvcmd=boot
__EOF__

: ==== copy all the images to one folder

[ -d image_folder/ ] || mkdir image_folder/
cp kernel/arch/arm/boot/uImage image_folder/
cp u-boot/u-boot.img image_folder/
cp u-boot/MLO image_folder/
cp out/target/product/beaglebone/rootfs.tar.bz2 image_folder/
cp uEnv.txt image_folder/

: ==== get the Media_Clips folder and the mkmmc-android.sh script from the SD card prebuilt image

cp -a ~/BeagleBone/Media_Clips/ image_folder/
cp ~/BeagleBone/mkmmc-android.sh image_folder/

: == Connect an SD card to the Host machine and prepare the card for booting

sd_card_mounted_dev_folder=/dev/sdc
mount | grep $sd_card_mounted_dev_folder
cd image_folder/
sudo ./mkmmc-android.sh $sd_card_mounted_dev_folder MLO u-boot.img uImage uEnv.txt rootfs.tar.bz2 Media_Clips

: == Safely remove the SD card and put it on the BeagleBone for Booting.

: = $0: SUCCESS
exit 0
