#!/bin/bash

set -x
PS4='[ $(date +%T) ] '

add-apt-repository "deb http://archive.canonical.com/ lucid partner"
add-apt-repository "deb-src http://archive.canonical.com/ubuntu lucid partner"
apt-get update
apt-get install git-core gnupg sun-java6-jdk flex bison gperf libsdl-dev libesd0-dev libwxgtk2.6-dev build-essential zip curl libncurses5-dev zlib1g-dev minicom tftpd uboot-mkimage expect
update-java-alternatives -s java-6-sun

exit 0
