#!/bin/bash -eux

set -x
PS4='[ $(date +%T) ] '

: == Make sure ~/bin/ exists, and is in $PATH

[ -d ~/bin/ ] || mkdir ~/bin/
PATH=~/bin:$PATH

: == Download the repo script and ensure it is executable:

if ! type repo; then
  curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo
  chmod a+x ~/bin/repo
fi

: == Download the BeagleBone prebuilt image
if ! [ -d ~/BeagleBone ]
  cd
  curl http://software-dl.ti.com/dsps/dsps_public_sw/sdo_tii/TI_Android_DevKit/TI_Android_GingerBread_2_3_4_DevKit_2_1_1/exports/BeagleBone.tar.gz > /tmp/BeagleBone.tar.gz
  tar -zxvf /tmp/BeagleBone.tar.gz
fi
  

: == Clone sources from www.gitorious.org/rowboat repository

[ -d $HOME/rowboat-android/ ] || mkdir $HOME/rowboat-android

cd $HOME/rowboat-android
repo init -u git://gitorious.org/rowboat/manifest.git -m rowboat-gingerbread-am335x.xml

repo sync

: == All done
exit 0
